dist: xenial
language: python
cache: pip
env:
- TEST_CMD="pytest --cov bear_todo_counter"
install:
  - pip install --upgrade pip
  - pip install poetry
  - poetry install -v
script:
- $TEST_CMD
after_success:
- coveralls
notifications:
  on_success: change
  on_failure: always
matrix:
  include:
    - name: "black"
      python: 3.7
      env:
        - TEST_CMD="black --check --verbose ."
    - name: "3.7"
      python: 3.7
    - name: "3.8"
      python: 3.8
    - name: "3.9"
      python: 3.9
