dist: xenial
language: python
python:
  - "3.6"
cache: pip
env:
- TEST_CMD="pytest --cov main"
install:
- pip install -r requirements.txt
script:
- $TEST_CMD
after_success:
- coveralls
notifications:
  on_success: change
  on_failure: always
matrix:
  include:
    - name: "black"
      python: 3.6
      env:
        - TEST_CMD="black --check --verbose ."
